[package]
name = "gamestate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
image = "0.24"
imageproc = "0.23"
rusttype = "0.9"
